MosquitoLab.WingBank/Controllers/DownloadController.cs
using System;
using System.Web.Mvc;
using MosquitoLab.Domain.Individuals.Commands.Input;
using MosquitoLab.Domain.Individuals.Commands.Output;
using MosquitoLab.Domain.Individuals.Handlers;

namespace MosquitoLab.WingBank.Controllers
{
    public class DownloadController : Controller
    {
        private readonly WingHandler _handler;

        public DownloadController(WingHandler handler)
        {
            _handler = handler;
        }

        public FileResult Wings(DownloadWingCommand command)
        {
            var result = (DownloadWingCommandResult)_handler.Handle(command);
            if (!command.IsValid()) return null;
            return File(result.FileName, result.ContentType,  result.DownloadFileName);
        }
    }
}

MosquitoLab.WingBank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MosquitoLab.WingBank.Controllers
{
    public class HomeController : Controller
    {
        public PartialViewResult Index()
        {
            return PartialView("Search");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MosquitoLab.WingBank/Controllers/InstructionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MosquitoLab.WingBank.Controllers
{
    public class InstructionsController : Controller
    {
        // GET: Instructions
        public ActionResult Index()
        {
            return View();
        }
    }
}

MosquitoLab.WingBank/Controllers/ResultController.cs
using System.Web.Mvc;
using MosquitoLab.Application.Individuals.Services.Interfaces;
using MosquitoLab.Domain.Individuals.Filters;
using MosquitoLab.Domain.Individuals.Repositories;
using MosquitoLab.WingBank.Helpers;

namespace MosquitoLab.WingBank.Controllers
{
    public class ResultController : Controller
    {
        private readonly IWingImageAppService _appService;
        private readonly IWingImageRepository _wingImageRepository;

        public ResultController(IWingImageAppService appService, IWingImageRepository wingImageRepository)
        {
            _appService = appService;
            _wingImageRepository = wingImageRepository;
        }

        // GET: Result
        public ActionResult Index(WingFilter filter = null)
        {
            var wings = _wingImageRepository.Find(filter);
            return View(wings);
        }

        public JsonResultHelper Find(WingFilter filter = null)
        {
            var wings = _wingImageRepository.Find(filter);
            return new JsonResultHelper(wings, JsonRequestBehavior.AllowGet);
        }

        public JsonResultHelper ByIds(string wingsIds)
        {
            var wings = _wingImageRepository.GetByIds(wingsIds);
            return new JsonResultHelper(wings, JsonRequestBehavior.AllowGet);
        }
    }
}

MosquitoLab.WingBank/Controllers/SearchController.cs
using System.Configuration;
using System.Web.Mvc;
using MosquitoLab.Application.Common.Services.Interfaces;
using MosquitoLab.Domain.Accounts.Filters;
using MosquitoLab.WingBank.Helpers;

namespace MosquitoLab.WingBank.Controllers
{
    public class SearchController : Controller
    {
        private readonly IAdvancedSearchAppService _appService;

        public SearchController(IAdvancedSearchAppService appService)
        {
            _appService = appService;
        }

        // GET: Search
        public ActionResult Index()
        {
            //var model = _appService.GetAdancedSearchFilters();
            ViewBag.GoogleMapsKey = ConfigurationManager.AppSettings["GoogleMapsKey"];
            return View();
        }

        public JsonResultHelper GetDatabaseInfo()
        {
            var result = _appService.GetDatabaseInfo();
            return new JsonResultHelper(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResultHelper GetFamlies()
        {
            var result = _appService.GetFamlies();
            return new JsonResultHelper(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResultHelper GetSubfamilies(AdancedSearchFilter filter)
        {
            var result = _appService.GetSubfamilies(filter);
            return new JsonResultHelper(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResultHelper GetTribes(AdancedSearchFilter filter)
        {
            var result = _appService.GetTribes(filter);
            return new JsonResultHelper(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResultHelper GetSpecies(AdancedSearchFilter filter)
        {
            var result = _appService.GetSpecies(filter);
            return new JsonResultHelper(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResultHelper GetSubspecies(AdancedSearchFilter filter)
        {
            var result = _appService.GetSubspecies(filter);
            return new JsonResultHelper(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResultHelper GetGenus(AdancedSearchFilter filter)
        {
            var result = _appService.GetGenus(filter);
            return new JsonResultHelper(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResultHelper GetSubgenus(AdancedSearchFilter filter)
        {
            var result = _appService.GetSubgenus(filter);
            return new JsonResultHelper(result, JsonRequestBehavior.AllowGet);
        }
    }
}

MosquitoLab.WingBank/Controllers/TermsController.cs
using System.Web.Mvc;

namespace MosquitoLab.WingBank.Controllers
{
    public class TermsController : Controller
    {
        // GET: Terms
        public ActionResult Index()
        {
            return View();
        }

        // GET: Terms
        public PartialViewResult Partial()
        {
            return PartialView(@"Index");
        }

    }
}

MosquitoLab.WingBank/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MosquitoLab.WingBank/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MosquitoLab.WingBank/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MosquitoLab.WingBank/Views/Home/Search.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MosquitoLab - Wingbank</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        body {
            background: #fff !important;
        }
    </style>
</head>
<body>
    <div class="search-center">

        <div class="search-box">

            <div class="col-lg-12">
                <img class="wingbank-logo wingbank-logo-full" src="~/Content/Images/Logo.png" />
            </div>
            <div class="col-lg-12">
                @Html.Partial("~/Views/Shared/Components/_SimpleSearch.cshtml")
            </div>
            <div class="col-lg-12">
                <br />
                @Html.ActionLink("Advanced Search", "Index", "Search") | 
                @Html.ActionLink("Instructions", "Index", "Instructions") |
                @Html.ActionLink("Terms of use", "Index", "Terms")
            </div>

            <div class="col-md-12">
                <p dabase-info></p>
            </div>
        </div>
        
        <footer class="footer">

            <center style="margin-top: 100px">
                <p>&copy; @DateTime.Now.Year - MosquitoLab - WingBank </p>
                <p>
                   Found an error? Contact us. <a href="mail:wingbank@butantan.gov.br">wingbank@butantan.gov.br</a>
                </p>
            </center>

        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")


    @{
        var h = HttpContext.Current.Request.ApplicationPath;
    }

    <script>
    var _env = { host: "@(h == "/" ? h : h + "/" )" };
    </script>

    <script src="~/Content/app/environment/environment.js"></script>
    <script src="~/Content/app/search/database-info.js"></script>
</body>
</html>

MosquitoLab.WingBank/Views/Instructions/Index.cshtml
@{ViewBag.Title = "Instructions";}

<div class="justified-text">

    <h2>INSTRUCTIONS</h2>

    <h3>To search</h3>
    <p>
        1) To this you do not need be registered. <br />
        2) You can search in two ways: <br />
        a) Basic search, writing what information you want to search <br />
        b) Advanced search, in which you can specify details of your search <br />
    </p>

    <p>
        IMPORTANT: If you want search by coordinates, you need write them in decimal pattern, and will
        need to be exactly identical to the registered in the Wingbank, in other words, if just one number
        will be different, perhaps you will not find what you search. So, be careful with this field.
    </p>

    @*<h3>To collaborate with Wingbank</h3>
        <p>
            <strong>First step</strong>
        <p>
            1) Register
            2) Wait to receive an e-mail confirming that you have registered successfully in Wingbank.
            IMPORTANT: Your images MUST belong to a scientific article that has already been published.
            Second step
        </p>
        <p>
            1) Login
            2) Go to the image data registration page (Bank &gt; Image Upload) and fill out all the fields
            3) Add your images
        </p>
        <p>
            <b> IMPORTANT:</b> Your image should contain the size scale and/or related information about
            resolution and technical devices used to produce it (ex.: stereoscope Leica S6D, camera
            DFC320, 4.0x Zoom, and when was possible, an image with size scale).
        </p>

        <p>
            4) Accept the Terms and Conditions. When you accept the Terms and Conditions, you are confirming
            that all the contents of the files being uploaded (and the files referred to by the URL and DOI) were
            written by you.
        </p>*@
    <p>
        <ul>
            <li>
                If you need specific and complete address, please contact us.
            </li>
            <li>
                If you need specific information of person responsible by some process (from sampling to taxonomic identification), please contact us.: <a href="mail:wingbank@butantan.gov.br ">wingbank@butantan.gov.br </a>
            </li>
        </ul>


    </p>

</div>

MosquitoLab.WingBank/Views/Search/Index.cshtml
@using MosquitoLab.Domain.Common.Dto
@{
    ViewBag.Title = "Advanced Search";
    ViewBag.HiddenAdvancedSearch = true;

    var model = (AdvancedSearchDto)Model;

}
<form method="GET" action="@Url.Action("Index", "Result")">

    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">Sampling</div>
                <div class="panel-body panel-h-290">

                    <div class="padding-3  col-lg-3">
                        <div class="form-group  form-group-sm">
                            <label for="">Specific locality</label>
                            <input name="specificLocality" type="text" class="form-control input-sm" placeholder="Specific locality">
                        </div>
                    </div>

                    <div class="padding-3  col-lg-5">
                        <div class="form-group  form-group-sm">
                            <label for="">Locality</label>
                            <input id="locality" onFocus="geolocate()" name="locality" type="text" class="form-control input-sm" placeholder="Locality">
                        </div>
                    </div>

                    <div class="padding-3  col-lg-4">
                        <div class="form-group  form-group-sm">
                            <label for="">City</label>
                            <input id="administrative_area_level_2" name="city" type="text" class="form-control input-sm" placeholder="City">
                        </div>
                    </div>

                    <div class="padding-3  col-lg-4">
                        <div class="form-group  form-group-sm">
                            <label for="">State / Province</label>
                            <input name="state" type="text" class="form-control input-sm" id="administrative_area_level_1" placeholder="State / Province">
                        </div>
                    </div>

                    <div class="padding-3  col-lg-4">
                        <div class="form-group  form-group-sm">
                            <label for="">Country</label>
                            <input name="country" type="text" class="form-control input-sm" id="country" placeholder="Country">
                        </div>
                    </div>


                    <div class="padding-3  col-lg-4">
                        <div class="form-group  form-group-sm">
                            <label for="">Date</label>
                            <input name="Date" type="text" class="form-control input-sm" data-mask="0000/00/00" placeholder="ex: yyyy/mm/dd">
                        </div>
                    </div>

                    <div class="padding-3  col-lg-4">
                        <div class="form-group  form-group-sm">
                            <label for="">Latitude</label>
                            <input name="latitude" type="text" class="form-control input-sm" id="latitude" placeholder="ex: 44.555,00">
                        </div>
                    </div>


                    <div class="padding-3  col-lg-4">
                        <div class="form-group  form-group-sm">
                            <label for="">Longitude</label>
                            <input name="longitude" type="text" class="form-control input-sm" placeholder="ex: 44.555,00">
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">Individual</div>
                <div class="panel-body panel-h-290">
                    <div class="padding-3  col-lg-5">
                        <div class="form-group  form-group-sm">
                            <label for="">Gender</label>
                            <select name=gender "" class="form-control input-sm">
                                <option value="" selected>Select gender</option>
                                <option value="M">Male</option>
                                <option value="F">Female</option>
                            </select>
                        </div>
                    </div>
                    <div class="padding-3  col-lg-5">
                        <div class="form-group  form-group-sm">
                            <label for="">Wing side</label>
                            <select name="wingSide" class="form-control input-sm">
                                <option value="" selected>Select side</option>
                                <option value="L">Left</option>
                                <option value="R">Right</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Taxonomic Identification</div>
                <div class="panel-body ">

                            <div class="padding-3  col-lg-4">
                                <div class="form-group  form-group-sm">
                                    <label for="">Family</label>
                                    <select id="select-family" name="family" class="form-control input-sm">
                                        <option value="" selected>Select family</option>
                                    </select>
                                </div>
                            </div>
                            <div class="padding-3  col-lg-4">
                                <div class="form-group  form-group-sm">
                                    <label for="">Subfamily</label>
                                    <select id="select-subfamily" name="subfamily" class="form-control input-sm">
                                        <option value="" selected>Select subfamily</option>
                                    </select>
                                </div>
                            </div>
                            <div class="padding-3  col-lg-4">
                                <div class="form-group  form-group-sm">
                                    <label for="">Tribe</label>
                                    <select id="select-tribe" name="tribe" class="form-control input-sm">
                                        <option value="" selected>Select tribe</option>
                                    </select>
                                </div>
                            </div>
                            <div class="padding-3  col-lg-4">
                                <div class="form-group  form-group-sm">
                                    <label for="">Genus</label>
                                    <select id="select-genus" name="genus" class="form-control input-sm">
                                        <option value="" selected>Select genus</option>
                                    </select>
                                </div>
                            </div>


                    <!-- <div class="padding-3  col-lg-3">
                        <div class="form-group  form-group-sm">
                            <label for="">Subgenus</label>
                            <select id="select-subgenus" name="subgenus" class="form-control input-sm">
                                <option value="" selected>Select subgenus</option>
                            </select>
                        </div>
                    </div> -->
                    <div class="padding-3  col-lg-4">
                        <div class="form-group  form-group-sm">
                            <label for="">Specific epithet</label>
                            <select id="select-specie" name="specie" class="form-control input-sm">
                                <option value="" selected>Select specific epithet</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Institution</div>
                <div class="panel-body ">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="padding-3  col-lg-4">
                                <div class="form-group  form-group-sm">
                                    <label for="">Institution name</label>
                                    <input name="institutionName" type="text" class="form-control input-sm" placeholder="Institution name">
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="padding-3  col-lg-4">
                        <div class="form-group  form-group-sm">
                            <label for="">MosquitoLab Code</label>
                            <input name="mosquitoLabCode" type="text" class="form-control input-sm" placeholder="MosquitoLab code">
                        </div>
                    </div>
                    <div class="padding-3  col-lg-5">
                        <div class="form-group  form-group-sm">
                            <label for="">LECZ Code (Laboratório Especial de Coleções Zoológicas)</label>
                            <input name="lecz" type="text" class="form-control input-sm" placeholder="LECZ Code (Laboratório Especial de Coleções Zoológicas)">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    @section PageAction{
        <button type="submit" class="btn btn-primary btn-lg active col-lg-2">Go!</button>
    </form>
    }
    @section scripts {



        <script src="~/Content/app/advanced-search/advanced-search.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=@ViewBag.GoogleMapsKey&libraries=places&callback=initAutocomplete"></script>

    }

MosquitoLab.WingBank/Views/Shared/Components/_SimpleSearch.cshtml
<form action="@Url.Action("Index", "Result")" method="get">
    <div class="input-group input-group-lg">
        <input type="text" name="text" class="form-control input-lg" placeholder="Search for...">
        <span class="input-group-btn">
            <button class="btn btn-default" onclick="location.href = '@Url.Action("Index", "Result")'" type="submit">Go!</button>
        </span>
    </div>
</form>

MosquitoLab.WingBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="Mon, 22 Jul 2002 11:12:01 GMT">	
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    <title>@ViewBag.Title - WingBank</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/vendors/css")
    @RenderSection("stylesheet", required: false)
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="glyphicon glyphicon-align-justify"></span>
                </button>
                <!--@Html.ActionLink("<img>", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })-->
                <a href="@Url.Action("Index", "Home")">
                    <img class="wingbank-logo wingbank-logo-min" src="@Url.Content("~/Content/Images/Logo.png")" , alt="Home" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <div class="col-lg-6 col-sm-6 col-md-6   nav-search">
                    <div class="col-lg-8 col-sm-7 col-md-7 ">
                        @Html.Partial("~/Views/Shared/Components/_SimpleSearch.cshtml")
                    </div>
                    @{ if (ViewBag.HiddenAdvancedSearch == false || ViewBag.HiddenAdvancedSearch == null)
                        {
                            <div class="col-lg-4 col-sm-5 col-md-5">
                                <div class="nav-link">
                                    @Html.ActionLink("Advanced Search", "Index", "Search")
                                </div>
                            </div>
                        }
                    }
                </div>
                <div class="col-lg-4 pull-right">

                    <ul class="nav navbar-nav navbar-right">
                        @*<li>@Html.ActionLink("Home", "", "Home")</li>*@
                        <!-- <li class="selected-files-modal" style="cursor: pointer;" title="Selected files"><a> <i class="glyphicon glyphicon-download-alt"> </i> (<span class="selected-files-counter">0</span>)  </a></li> -->
                        <li>@Html.ActionLink("Instructions", "Index", "Instructions")</li>
                        <li>@Html.ActionLink("Terms of use", "Index", "Terms")</li>
                        @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@ 
                    </ul>

                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="col-lg-12">
            @RenderSection("GridAction", required: false)
        </div>
        <fieldset>
            <legend> / @ViewBag.Title </legend>
            @RenderBody()
        </fieldset>
        <div class="col-lg-12 page-action">
            @RenderSection("PageAction", required: false)
        </div>
        <footer class="footer">

            <center>
                <p>&copy; @DateTime.Now.Year - MosquitoLab - WingBank </p>
                <p>
                    Found an error? Contact us. <a href="mail:wingbank@butantan.gov.br">wingbank@butantan.gov.br</a>
                </p>
            </center>

        </footer>
    </div>

    @{
        var h = HttpContext.Current.Request.ApplicationPath;
    }

    <script>
    var _env = { host: "@(h == "/" ? h : h + "/" )" };
    </script>

    <script src="~/Content/app/environment/environment.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Content/vendors/js")

    <script src="~/Content/app/app.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>